name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run tests
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
          
  merge-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: develop
        fetch-depth: 0

    - name: Setup Git identity
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Fetch main branch
      run: |
        git fetch origin main
        git checkout main

    - name: Check for merge conflicts with main
      run: |
        git merge develop --no-commit --no-ff
        merge_status=$?
        if [ $merge_status -ne 0 ]; then
          echo "Merge conflict with main branch"
          git merge --abort
          exit 1
        else
          echo "No merge conflict with main branch"
        fi
        
  merge:
    needs: [test, merge-check]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: develop
        fetch-depth: 0

    - name: Setup Git identity
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Merge develop into main
      run: |
        git fetch origin main
        git checkout main
        git merge --no-ff develop -m "Merging develop into main"
        git remote set-url origin https://x-access-token:${GIT_AUTH_TOKEN}@github.com/milhe99/super-fancy-stock-app.git
        git push origin main
      env:
        GIT_AUTH_TOKEN: ${{ secrets.ACTIONKEY }}
