name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run tests
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports
          
  merge-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - run: |
            git config --global user.email "tuukjazz@student.jyu.fi"
            git config --global user.name "Tuukjazz"

      # Add any necessary setup steps here
      
      # Ensure the branch is up-to-date with the main branch
      - name: Sync branch with main
        run: git fetch origin main && git merge origin/main --no-ff --allow-unrelated-histories

      # Check if the merge would result in conflicts
      - name: Check for merge conflicts
        run: git diff --quiet || { echo "Merge conflict detected! Resolve conflicts before merging."; }
